### ISSUE TITLE
Better way to handle, esp. for IE browsers

### ISSUE THREAD

**Issue by manikantag** [lukehorvat/angular-request-cache-disabler#1]
Hi,

This is not actually an issue, but a suggestion about better approach.

Though your trick of adding some random query param works in all cases, there is a better way of doing it - using headers.

I m using the below script to tell IE browsers not to cache: https://github.com/manikantag/angular-utils/blob/master/src/http-nocache.js

**Comment by lukehorvat** [comment]
I am aware of other potential solutions out there involving headers, but couldn't find a consensus on whether they _always_ worked. For example, [here](http://stackoverflow.com/a/19771501) your solution using `If-Modified-Since` is purported not to work in some cases.

My solution is based on the "industry standard" cache disabling settings found in [ExtJS](http://docs.sencha.com/extjs/5.0.1/#!/api/Ext.data.proxy.Ajax-cfg-noCache), [jQuery](http://api.jquery.com/jQuery.ajax/#jQuery-ajax-settings), and [MooTools](http://mootools.net/docs/core/Request/Request). It's the safer, better approach.
